# Dependencies
markdown:         kramdown

# Permalinks

# Setup
title:            Space
tagline:          'A Jekyll theme'
description:      'This is a Jekyll version of the Hyperspace HTML5UP website template. It has three post types - post, page and feature.'
url:              https://at-publishing.github.io/
baseurl:          hyperspace-jekyll

featurestagline:  'Phasellus convallis elit id ullamcorper pulvinar. Duis aliquam turpis mauris, eu ultricies erat malesuada quis. Aliquam dapibus, lacus eget hendrerit bibendum, urna est aliquam sem, sit amet imperdiet est velit quis lorem.'

gems:             [jekyll-paginate]

author:
  name:           'JMT'
  url:            https://bitbucket.org/_xin_chao
  uri:            https://bitbucket.org/_xin_chao

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/AT-Publishing/hyperspace-jekyll

# social
email:            admin@example.com
telegram:         https://t.me/sth
facebook:         https://facebook.com
twitter:          https://twitter.com
instagram:
linkedin:

projects: ['https://tadada.com', 'http://sth.com']


collections:
  - features

collections:
  features:
    output: true
    permalink: /:collection/:slug
